# -*- coding: utf-8 -*-
"""Info_Frutas_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T36-wjgET96UdVKqPbO_7L4AzR5s-r-Z
"""
%%writefile app.py
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import requests
from urllib.error import URLError
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Datos para los gráficos
opciones = ["A", "B", "C"]
valores_a = np.random.randint(1, 10, size=10)
valores_b = np.random.randint(1, 10, size=10)
valores_c = np.random.randint(1, 10, size=10)

# Crear el gráfico de barras para cada opción
def grafico_barras(opcion, valores):
    fig, ax = plt.subplots()
    ax.bar(range(len(valores)), valores)
    ax.set_xticks(range(len(valores)))
    ax.set_xticklabels([str(i) for i in range(1, len(valores)+1)])
    ax.set_xlabel("Índice")
    ax.set_ylabel("Valor")
    ax.set_title(f"Gráfico de barras para la opción {opcion}")
    st.pyplot(fig)

# Preguntar al usuario por la opción
opcion_seleccionada = st.selectbox("Selecciona una opción:", opciones)

# Mostrar el gráfico correspondiente a la opción seleccionada
if opcion_seleccionada == "A":
    grafico_barras(opcion_seleccionada, valores_a)
elif opcion_seleccionada == "B":
    grafico_barras(opcion_seleccionada, valores_b)
elif opcion_seleccionada == "C":
    grafico_barras(opcion_seleccionada, valores_c)
